"""组件注册表 + 按序拼接 + 校验门（契约 issue #1 / 流水线 issue #4）。

校验门语义：任何组件缺失、抛错或产出空串 → 整体拒绝产出，
绝不写半成品 README；写文件只做原子替换，失败路径不触碰旧文件。
"""

import importlib
import os
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from main.config import enabled_sections, section_config

RenderFn = Callable[[dict[str, Any], dict[str, Any]], str]

GENERATED_MARKER = (
    "<!-- AUTO-GENERATED by Jason-skd profile pipeline — "
    "edit profile.yaml instead; README.md is never hand-edited -->"
)

# section → data/*.json 基名（None 表示无数据组件）
SECTION_DATA: dict[str, str | None] = {
    "banner": None,
    "typing": None,
    "stats": "stats",
    "languages": "languages",
    "org_card": "org",
    "recent_project": "recent",
}


class AssemblyError(Exception):
    """校验门拒绝：组件缺失 / 组件异常 / 空产出。"""


def import_registry() -> dict[str, RenderFn]:
    """从 main.components.<name> 动态收集 render()（组件层 #3 集成后生效）。"""
    registry: dict[str, RenderFn] = {}
    for name in SECTION_DATA:
        try:
            module = importlib.import_module(f"main.components.{name}")
        except ModuleNotFoundError:
            continue
        render = getattr(module, "render", None)
        if callable(render):
            registry[name] = render  # type: ignore[assignment]
    return registry


def fixture_registry(fixtures_dir: Path) -> dict[str, RenderFn]:
    """fixtures/components_output/<name>.md 作为组件产出替身（离线端到端）。"""
    base = fixtures_dir / "components_output"

    def _make(name: str) -> RenderFn:
        def render(config: dict[str, Any], data: dict[str, Any]) -> str:
            path = base / f"{name}.md"
            if not path.is_file():
                raise FileNotFoundError(f"fixture output missing: {path}")
            return path.read_text(encoding="utf-8")

        return render

    return {name: _make(name) for name in SECTION_DATA if (base / f"{name}.md").is_file()}


def render_all(
    profile: dict[str, Any],
    data_map: dict[str, Any],
    registry: dict[str, RenderFn],
) -> dict[str, str]:
    """按启用顺序渲染全部组件；任一失败抛 AssemblyError（校验门）。"""
    outputs: dict[str, str] = {}
    missing: list[str] = []
    for name in enabled_sections(profile):
        render = registry.get(name)
        if render is None:
            missing.append(name)
            continue
        data_key = SECTION_DATA[name]
        data = data_map.get(data_key, {}) if data_key else {}
        try:
            rendered = render(section_config(profile, name), data)
        except Exception as exc:
            raise AssemblyError(f"component {name!r} raised: {exc}") from exc
        if not isinstance(rendered, str) or not rendered.strip():
            raise AssemblyError(f"component {name!r} produced empty output")
        outputs[name] = rendered.rstrip("\n")
    if missing:
        raise AssemblyError(f"missing components: {missing}（components 层 #3 尚未集成或未注册）")
    return outputs


def assemble(
    profile: dict[str, Any],
    data_map: dict[str, Any],
    registry: dict[str, RenderFn],
    repo_root: Path,
) -> str:
    """拼接最终 README：templates/README.md.j2 存在则走模板，否则纯拼接。"""
    outputs = render_all(profile, data_map, registry)
    template_path = repo_root / "templates" / "README.md.j2"
    if template_path.is_file():
        env = Environment(
            loader=FileSystemLoader(template_path.parent),
            autoescape=False,
            keep_trailing_newline=True,
        )
        template = env.get_template(template_path.name)
        return template.render(sections=outputs, profile=profile)
    # v1.2：段落间 --- 分割线，与模板 join 语义一致（模板缺席时的回落路径）
    body = "\n\n---\n\n".join(outputs.values())
    return f"{GENERATED_MARKER}\n\n{body}\n"


def write_atomic(path: Path, content: str) -> None:
    """先写临时文件再原子替换——任何失败都不触碰旧 README。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise
