const std = @import("std");
const config = @import("config.zig");
const payload = @import("page_payload.zig");
const render_page = @import("render_page.zig");
const fixture = @import("render_test.zig");
const allocator = std.testing.allocator;

const prefix = "<!-- AUTO-GENERATED by Jason-skd profile pipeline — edit profile.yaml instead; README.md is never hand-edited -->\n\n";
const footer = "\n\n<p align=\"center\">\n  <img src=\"https://capsule-render.vercel.app/api?type=waving&amp;color=0:1a1b26,100:7aa2f7&amp;height=120&amp;section=footer&amp;reversal=true\" alt=\"footer\" width=\"100%\" />\n</p>\n";

test "complete page golden preserves order separators marker and footer" {
    const result = try render_page.assemble(allocator, &fixture.cfg, &fixture.page);
    defer allocator.free(result);
    try std.testing.expectEqualStrings(@embedFile("render_fixtures/page.md"), result);
}

test "configured reverse order is respected" {
    var cfg = fixture.cfg;
    cfg.sections = &.{ .recent_project, .banner };
    const result = try render_page.assemble(allocator, &cfg, &fixture.page);
    defer allocator.free(result);
    try std.testing.expectEqualStrings(prefix ++ @embedFile("render_fixtures/recent_project.md") ++ "\n\n---\n\n" ++ @embedFile("render_fixtures/banner.md") ++ footer, result);
}

test "disabled sections require no payload and leave no separators at either edge" {
    var cfg = fixture.cfg;
    cfg.sections = &.{ .org_card, .banner, .recent_project };
    cfg.org_card.enabled = false;
    cfg.recent_project.enabled = false;
    var page = fixture.page;
    page.organization = null;
    page.recent_project.window_days = 0;
    const result = try render_page.assemble(allocator, &cfg, &page);
    defer allocator.free(result);
    try std.testing.expectEqualStrings(prefix ++ @embedFile("render_fixtures/banner.md") ++ footer, result);
    cfg.sections = &.{ .banner, .org_card, .typing, .recent_project };
    const middle = try render_page.assemble(allocator, &cfg, &page);
    defer allocator.free(middle);
    try std.testing.expectEqualStrings(prefix ++ @embedFile("render_fixtures/banner.md") ++ "\n\n---\n\n" ++ @embedFile("render_fixtures/typing.md") ++ footer, middle);
}

test "duplicate and all-disabled or absent sections fail" {
    var cfg = fixture.cfg;
    cfg.sections = &.{ .banner, .banner };
    try std.testing.expectError(error.DuplicateSection, render_page.assemble(allocator, &cfg, &fixture.page));
    cfg.sections = &.{ .org_card, .org_card };
    cfg.org_card.enabled = false;
    try std.testing.expectError(error.DuplicateSection, render_page.assemble(allocator, &cfg, &fixture.page));
    cfg.sections = &.{.org_card};
    try std.testing.expectError(error.EmptyPage, render_page.assemble(allocator, &cfg, &fixture.page));
    cfg.sections = &.{};
    try std.testing.expectError(error.EmptyPage, render_page.assemble(allocator, &cfg, &fixture.page));
}

test "enabled missing and invalid sections fail after earlier sections rendered" {
    var page = fixture.page;
    page.languages = &.{};
    try std.testing.expectError(error.MissingLanguages, render_page.assemble(allocator, &fixture.cfg, &page));
    page = fixture.page;
    page.organization = null;
    try std.testing.expectError(error.MissingOrganization, render_page.assemble(allocator, &fixture.cfg, &page));
    var cfg = fixture.cfg;
    cfg.typing.lines = &.{};
    try std.testing.expectError(error.InvalidSection, render_page.assemble(allocator, &cfg, &fixture.page));
    page = fixture.page;
    page.recent_project.selection.project.github_url = "";
    try std.testing.expectError(error.InvalidSection, render_page.assemble(allocator, &fixture.cfg, &page));
}

test "window mismatch cannot silently mislabel collected data" {
    var page = fixture.page;
    page.stats.window_days = 30;
    try std.testing.expectError(error.InvalidWindow, render_page.assemble(allocator, &fixture.cfg, &page));
    page = fixture.page;
    page.recent_project.window_days = 60;
    try std.testing.expectError(error.InvalidWindow, render_page.assemble(allocator, &fixture.cfg, &page));
    var cfg = fixture.cfg;
    cfg.window_days = 0;
    try std.testing.expectError(error.InvalidWindow, render_page.assemble(allocator, &cfg, &fixture.page));
}

fn allocationScenario(gpa: std.mem.Allocator) !void {
    const result = try render_page.assemble(gpa, &fixture.cfg, &fixture.page);
    defer gpa.free(result);
    try std.testing.expectEqualStrings(@embedFile("render_fixtures/page.md"), result);
}
test "assembly releases every intermediate allocation on OOM" {
    try std.testing.checkAllAllocationFailures(allocator, allocationScenario, .{});
}

test "configuration through payload to page carries dynamic window and fractional languages" {
    const github = @import("github_workflow.zig");
    const activity = @import("git_activity.zig");
    const languages = @import("language_stats.zig");
    var diagnostic: config.Diagnostic = .{};
    const parsed = try config.parse(allocator,
        \\login: Jason-skd
        \\timezone: Asia/Shanghai
        \\theme:
        \\author_emails:
        \\  - owner@example.test
        \\window_days: 90
        \\sections:
        \\  - stats
        \\  - languages
        \\  - recent_project
        \\typing:
        \\  width: 640
    , &diagnostic);
    defer parsed.deinit();
    const profile: github.Profile = .{
        .login = "Jason-skd",
        .access = .public_only,
        .owned_repositories = &.{},
        .contributed_repositories = &.{},
        .contributions = .{ .calendar_total = 0, .active_days = 0, .commits = 0, .issues = 0, .pull_requests = 0, .reviews = 0, .repositories_created = 0, .viewer_inaccessible = 0 },
    };
    const aggregate: activity.Aggregate = .{ .repositories = &.{}, .repository_count = 0, .unavailable_count = 0, .commit_count = 0, .text_additions = 0, .text_deletions = 0, .binary_files = 0, .renamed_files = 0 };
    const lang: languages.Result = .{ .allocator = allocator, .entries = &.{ .{ .name = "Zig", .weight = 2, .percentage_tenths = 667 }, .{ .name = "C", .weight = 1, .percentage_tenths = 333 } } };
    const owned = try payload.build(allocator, .{ .config = &parsed.value, .profile = &profile, .organization = null, .repository_metadata = &.{}, .activity = &aggregate, .languages = &lang, .now_utc = 1_700_000_000 });
    defer owned.deinit();
    const result = try render_page.assemble(allocator, &parsed.value, &owned.value);
    defer allocator.free(result);
    for ([_][]const u8{ "📊 Last 90 Days", "Last 90 days · incl.", "No commits to show in the last 90 days", "Zig 66.7%", "C 33.3%" }) |expected| try std.testing.expect(std.mem.indexOf(u8, result, expected) != null);
    try std.testing.expect(std.mem.indexOf(u8, result, "365") == null);
}
