//! Complete-page assembly; no output is exposed until every section succeeds.
const std = @import("std");
const config = @import("config.zig");
const payload = @import("page_payload.zig");
const render = @import("render.zig");

pub const Error = std.mem.Allocator.Error || error{
    DuplicateSection,
    EmptyPage,
    EmptySection,
    InvalidWindow,
    MissingLanguages,
    MissingOrganization,
    InvalidSection,
};

const marker = "<!-- AUTO-GENERATED by Jason-skd profile pipeline — edit profile.yaml instead; README.md is never hand-edited -->";

/// Borrows normalized config and completed payload. The caller must free the
/// successful result with allocator. Failure releases all intermediate storage;
/// file replacement and source-query window configuration belong to the caller.
pub fn assemble(allocator: std.mem.Allocator, cfg: *const config.Config, page: *const payload.Page) Error![]u8 {
    var seen: std.EnumSet(config.Section) = .empty;
    var enabled_count: usize = 0;
    for (cfg.sections) |section| {
        if (seen.contains(section)) return error.DuplicateSection;
        seen.insert(section);
        if (!enabled(section, cfg)) continue;
        enabled_count += 1;
        switch (section) {
            .stats => if (cfg.window_days == 0 or page.stats.window_days != cfg.window_days) return error.InvalidWindow,
            .recent_project => if (cfg.window_days == 0 or page.recent_project.window_days != cfg.window_days) return error.InvalidWindow,
            else => {},
        }
    }
    if (enabled_count == 0) return error.EmptyPage;

    var output: std.Io.Writer.Allocating = .init(allocator);
    defer output.deinit();
    var component: std.Io.Writer.Allocating = .init(allocator);
    defer component.deinit();
    output.writer.writeAll(marker ++ "\n\n") catch return error.OutOfMemory;
    var wrote = false;
    for (cfg.sections) |section| {
        if (!enabled(section, cfg)) continue;
        component.clearRetainingCapacity();
        writeSection(&component.writer, section, cfg, page) catch |err| switch (err) {
            error.WriteFailed => return error.OutOfMemory,
            error.MissingLanguages => return error.MissingLanguages,
            error.MissingOrganization => return error.MissingOrganization,
            error.InvalidSection => return error.InvalidSection,
        };
        const content = component.written();
        if (std.mem.trim(u8, content, " \t\r\n").len == 0) return error.EmptySection;
        if (wrote) output.writer.writeAll("\n\n---\n\n") catch return error.OutOfMemory;
        output.writer.writeAll(content) catch return error.OutOfMemory;
        wrote = true;
    }
    output.writer.writeAll("\n\n") catch return error.OutOfMemory;
    render.footer(&output.writer, &cfg.theme) catch return error.OutOfMemory;
    return output.toOwnedSlice();
}

fn enabled(section: config.Section, cfg: *const config.Config) bool {
    return switch (section) {
        .org_card => cfg.org_card.enabled,
        .recent_project => cfg.recent_project.enabled,
        else => true,
    };
}

fn writeSection(w: *std.Io.Writer, section: config.Section, cfg: *const config.Config, page: *const payload.Page) render.Error!void {
    switch (section) {
        .banner => try render.banner(w, &cfg.banner, &cfg.theme),
        .typing => try render.typing(w, &cfg.typing, &cfg.theme),
        .stats => try render.stats(w, &cfg.stats, &cfg.theme, &page.stats),
        .languages => try render.languages(w, &cfg.languages, page.languages),
        .org_card => try render.organization(w, &cfg.org_card, &(page.organization orelse return error.MissingOrganization)),
        .recent_project => try render.recentProject(w, &cfg.recent_project, &page.recent_project),
    }
}

test {
    _ = @import("render_page_test.zig");
}
